#!/usr/bin/env bash
# Configures a Nginx server so that /redirect_me is redirecting to another page
apt-get -y update
apt-get -y install nginx

echo 'Hello World!' > /usr/share/nginx/html/index.html

# stream editor. -i: to update the file
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx restart