#!/usr/bin/env bash
# This script creates a file with its pid, displays message indefinitely, displays another message when receive a SIGTERM, displays another message when get SIGINT, deletes file when receive a SIGQUIT or SIGTERM signal
pgrep -f 100-process_and_pid_file > /var/run/holbertonscript.pid
trap "{ rm /var/run/holbertonscript.pid ; echo I hate the kill command ; exit; }" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "{ rm /var/run/holbertonscript.pid ; exit; }" SIGQUIT
while :
do
	echo "To infinity and beyond"
	sleep 2
done
