#!/usr/bin/env bash
# This script manages daemon "manage_my_process"
pid_file="/var/run/my_process.pid"
do_start() {
	./manage_my_process &
	echo "$!" > "$pid_file"
}
do_stop() {
	kill "$(cat $pid_file)"
	rm $pid_file
}
case $1 in
	start)
		do_start
		echo "manage_my_process started"
		;;
	stop)
		do_stop
		echo "manage_my_process stopped"
		;;
	restart)
		do_stop
		do_start
		echo "manage_my_process restarted"
		;;
	*) echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
