#!/usr/bin/env bash
# This script checks if a file exists and different messages of the state of the file if it exists

file="holbertonschool"
if [ -e $file ]
then
	echo "holbertonschool file exists"
	if [ -s $file ]
	then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi
	if [ -f $file ]
	then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
