#!/usr/bin/env bash
# Configures server with nginx, adds redirection, custom 404 page, and header

sudo apt-get -y update
sudo apt-get -y install nginx

echo 'Hello World!' > /usr/share/nginx/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo sed -i '/listen 80 default_server;/a error_page 404 /404.html; location = /404.html {root /usr/share/nginx/html;internal;}' /etc/nginx/sites-available/default

sudo sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

sudo service nginx restart
